tabuada  =  int ( input ( 'Digite o numero da tabuada desejada: ' ))

print ( '-' * 20 )
print ( '{} * {:2} = {} ;' . formato ( tabuada , 0 , tabuada * 0 ))
print ( '{} * {:2} = {} ;' . formato ( tabuada , 1 , tabuada * 1 ))
print ( '{} * {:2} = {} ;' . formato ( tabuada , 2 , tabuada * 2 ))
print ( '{} * {:2} = {} ;' . formato ( tabuada , 3 , tabuada * 3 ))
print ( '{} * {:2} = {} ;' . formato ( tabuada , 4 , tabuada * 4 ))
print ( '{} * {:2} = {} ;' . formato ( tabuada , 5 , tabuada * 5 ))
print ( '{} * {:2} = {} ;' . formato ( tabuada , 6 , tabuada * 6 ))
print ( '{} * {:2} = {} ;' . formato ( tabuada , 7 , tabuada * 7 ))
print ( '{} * {:2} = {} ;' . formato ( tabuada , 8 , tabuada * 8 ))
print ( '{} * {:2} = {} ;' . formato ( tabuada , 9 , tabuada * 9 ))
print ( '{} * {:2} = {} ;' . formato ( tabuada , 10 , tabuada * 10 ))
print ( '-' * 20 )